apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NguyenQuangPhong/NguyenQuangPhong-aws-accelerator-p2.git
    targetRevision: HEAD
    path: cloud/w9/day-a/my-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
